In [2]:
import numpy as np

$Let A = UDV^*$

$ A^*A = VDU^*UDV = VD^2V^* $ &#8594; $ A^*AV = VD^2 $


$ AA^* = UDV^*VDU^* = UD^2U^* $ &#8594; $ AA^*U = UD^2 $

When a matrix is right-multiplied by a diagonal matrix, each column is multiplied by the diagonal term:

\begin{equation}[b_{1} ...,b_{n}]
\begin{pmatrix}\sigma^2_1&\\&\ddots\\&&\sigma_n^2\end{pmatrix}
[\sigma_{^2_{1}}b_{1}, ...,\sigma_{^2_{n}}b_{n}]
\end{equation}

The right-hand expressions are exactly the eigenvalue equations,

$ A^*Av_{i} = \sigma^2_{i}v_{i}, AA^*u_{i} = \sigma^2_{i}u_{i}$


In [3]:
A = np.array([[-1,2],[-3,2],[5,7]])
A

array([[-1,  2],
       [-3,  2],
       [ 5,  7]])

In [5]:
U, d, VT = np.linalg.svd(A)

In [6]:
U

array([[-0.12708324,  0.47409506,  0.87125411],
       [ 0.00164602,  0.87847553, -0.47778451],
       [-0.99189069, -0.0592843 , -0.11241989]])

In [7]:
VT

array([[-0.55798885, -0.82984845],
       [-0.82984845,  0.55798885]])

In [8]:
d

array([8.66918448, 4.10429538])

In [9]:
np.diag(d)

array([[8.66918448, 0.        ],
       [0.        , 4.10429538]])

In [10]:
D = np.concatenate((np.diag(d), [[0,0]]),axis=0)
D

array([[8.66918448, 0.        ],
       [0.        , 4.10429538],
       [0.        , 0.        ]])

In [11]:
np.dot(U, np.dot(D, VT))

array([[-1.,  2.],
       [-3.,  2.],
       [ 5.,  7.]])