In [3]:
import numpy as np

$Let A = UDV^*$

$ A^*A = VDU^*UDV = VD^2V^* $ &#8594; $ A^*AV = VD^2 $


$ AA^* = UDV^*VDU^* = UD^2U^* $ &#8594; $ AA^*U = UD^2 $

When a matrix is right-multiplied by a diagonal matrix, each column is multiplied by the diagonal term:

\begin{equation}[b_{1} ...,b_{n}]
\begin{pmatrix}\sigma^2_1&\\&\ddots\\&&\sigma_n^2\end{pmatrix}
[\sigma_{^2_{1}}b_{1}, ...,\sigma_{^2_{n}}b_{n}]
\end{equation}

The right-hand expressions are exactly the eigenvalue equations,

$ A^*Av_{i} = \sigma^2_{i}v_{i}, AA^*u_{i} = \sigma^2_{i}u_{i}$


In [5]:
A = np.array([[-1,2],[3,2],[5,7]])
A

array([[-1,  2],
       [ 3,  2],
       [ 5,  7]])

In [6]:
U, d, VT = np.linalg.svd(A)

In [7]:
U

array([[ 0.10655106, -0.85637177, -0.50524673],
       [ 0.3660941 ,  0.50623164, -0.78083586],
       [ 0.92445767, -0.10176896,  0.36745217]])

In [8]:
VT

array([[ 0.60354778,  0.79732684],
       [ 0.79732684, -0.60354778]])

In [9]:
d

array([9.30169873, 2.34059839])

In [10]:
np.diag(d)

array([[9.30169873, 0.        ],
       [0.        , 2.34059839]])

In [11]:
D = np.concatenate((np.diag(d), [[0,0]]),axis=0)
D

array([[9.30169873, 0.        ],
       [0.        , 2.34059839],
       [0.        , 0.        ]])

In [12]:
np.dot(U, np.dot(D, VT))

array([[-1.,  2.],
       [ 3.,  2.],
       [ 5.,  7.]])